# Generated by Django 2.0.7 on 2018-07-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fulltext',
            field=models.TextField(default='full text'),
            preserve_default=False,
        ),
    ]
